INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK) VALUES (1, 'Chicken', 900, 100);
INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK) VALUES (2, 'Apple', 800, 100);
INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK) VALUES (3, 'Rice', 400, 50);
INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK) VALUES (4, 'Orange', 500, 20);


