INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK) VALUES (1, 'Iphone', 900, 100);
INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK) VALUES (2, 'Samsung', 800, 100);
INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK) VALUES (3, 'Honor', 400, 50);
INSERT INTO PRODUCT (ID, NAME, PRICE, STOCK) VALUES (4, 'SolanaPhone', 500, 20);


